// File generated by the FlutterFire CLI (`flutterfire configure -p
// tasks-1903 --platforms=android,web`) against the real `tasks-1903`
// Firebase project. Do not hand-edit — re-run `flutterfire configure` if
// the project's apps change.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have only been configured for Android and '
          'Web in this project. Run `flutterfire configure` to add more '
          'platforms.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuRezUSc-V5ohQL691sNijfxXu9n1beck',
    appId: '1:1012303591315:web:4ca9c811a0b6d3465c5a66',
    messagingSenderId: '1012303591315',
    projectId: 'tasks-1903',
    authDomain: 'tasks-1903.firebaseapp.com',
    storageBucket: 'tasks-1903.firebasestorage.app',
    measurementId: 'G-Q7MQBKHF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRQymwI2gg0iiVvP86MNQGWV0HT5rZQvY',
    appId: '1:1012303591315:android:18e27642314309265c5a66',
    messagingSenderId: '1012303591315',
    projectId: 'tasks-1903',
    storageBucket: 'tasks-1903.firebasestorage.app',
  );
}
