// File generated by the FlutterFire CLI (`flutterfire configure -p
// tasks-1903 --platforms=android,web`) against the real `tasks-1903`
// Firebase project. Do not hand-edit the android/web blocks — re-run
// `flutterfire configure` if those apps change.
//
// The `ios` block below is a PLACEHOLDER added while adding iOS platform
// support and does NOT point at a real Firebase iOS app yet — no iOS app
// has been registered in the `tasks-1903` Firebase project. Firebase.
// initializeApp() will not fail at startup anymore (that UnsupportedError
// was the previous, harder failure mode), but any real Firebase Auth/
// Firestore/Messaging call on iOS will fail against these fake
// apiKey/appId values until this is replaced. To fix for real:
//   1. Firebase Console > tasks-1903 > Add app > iOS, bundle ID
//      `com.steadyprogress.steadyProgress` (see ios/Runner.xcodeproj).
//   2. Download the resulting GoogleService-Info.plist into ios/Runner/.
//   3. Run `flutterfire configure -p tasks-1903 --platforms=android,ios,web`
//      (or hand-copy the apiKey/appId/iosClientId values here) to replace
//      this placeholder block.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have only been configured for Android, iOS '
          'and Web in this project. Run `flutterfire configure` to add more '
          'platforms.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuRezUSc-V5ohQL691sNijfxXu9n1beck',
    appId: '1:1012303591315:web:4ca9c811a0b6d3465c5a66',
    messagingSenderId: '1012303591315',
    projectId: 'tasks-1903',
    authDomain: 'tasks-1903.firebaseapp.com',
    storageBucket: 'tasks-1903.firebasestorage.app',
    measurementId: 'G-Q7MQBKHF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRQymwI2gg0iiVvP86MNQGWV0HT5rZQvY',
    appId: '1:1012303591315:android:18e27642314309265c5a66',
    messagingSenderId: '1012303591315',
    projectId: 'tasks-1903',
    storageBucket: 'tasks-1903.firebasestorage.app',
  );

  // PLACEHOLDER — see the file-level comment above. Replace apiKey/appId
  // with the values from the real iOS GoogleService-Info.plist once that
  // app is registered in the tasks-1903 Firebase project.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:1012303591315:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '1012303591315',
    projectId: 'tasks-1903',
    storageBucket: 'tasks-1903.firebasestorage.app',
    iosBundleId: 'com.steadyprogress.steadyProgress',
  );
}
